(() => {
"use strict";
const CONFIG=window.APP_CONFIG||{}; const TRAIN=window.TRAINING_CASES||[];
const OFFLINE=new URLSearchParams(location.search).get('offline')==='1';
const STORE={profile:'hwa_v5_profile',session:'hwa_v5_session',drafts:'hwa_v5_drafts',receipts:'hwa_v5_receipts',practice:OFFLINE?'hwa_v5_practice_offline':'hwa_v5_practice'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s)); const now=()=>new Date().toISOString();
const state={profile:load(STORE.profile,null),session:load(STORE.session,{count:0,started_at:now()}),drafts:load(STORE.drafts,{}),receipts:load(STORE.receipts,[]),practice:load(STORE.practice,{done:[]}),mode:null,currentAssignment:null,currentCase:null,currentStartedAt:null,lang:'fr',submitting:false};
function load(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function configured(){return !OFFLINE&&Boolean(CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_ANON_KEY)}
async function rpc(name,p={}){if(!configured())throw new Error("Le site n’est pas encore relié à Supabase.");const u=`${CONFIG.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/rpc/${name}`;const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json',apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${CONFIG.SUPABASE_ANON_KEY}`},body:JSON.stringify(p)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||d?.details||t||`HTTP ${r.status}`);return d}
const first=d=>Array.isArray(d)?d[0]||null:d||null;
function setConnection(k,t){const e=$('#connectionBadge');e.className=`badge ${k}`;e.textContent=t}
async function checkBackend(){if(OFFLINE){setConnection('muted','Mode entraînement');$('#setupWarning').classList.remove('hidden');return false}if(!configured()){setConnection('bad','À configurer');$('#setupWarning').classList.remove('hidden');return false}try{const r=first(await rpc('annotation_service_status',{}));if(r?.status==='ok'){setConnection('ok','Connecté');$('#setupWarning').classList.add('hidden');return true}}catch(e){console.error(e)}setConnection('bad','Hors ligne');$('#setupWarning').classList.remove('hidden');return false}
function setScreen(n){$$('.screen').forEach(x=>x.classList.remove('active'));$(`#screen-${n}`)?.classList.add('active');$$('.step').forEach(x=>x.classList.toggle('active',x.dataset.screen===n));scrollTo({top:0,behavior:'smooth'});if(n==='done')refreshDone()}
function bgLevel(b){return ['biomedical','medical'].includes(b)?2:b==='science'?1:0}
function prefill(){if(!state.profile)return;$('#annotatorName').value=state.profile.display_name||'';$('#background').value=state.profile.background||'';$('#consent').checked=true}
function validateLocalProfile(){if(!$('#background').value)throw new Error('Choisis ton type de formation.');if(!$('#consent').checked)throw new Error('Ton accord est nécessaire pour participer.')}
async function ensureProfile(){validateLocalProfile();if(state.profile?.annotator_id&&state.profile?.access_token)return state.profile;if(!configured())throw new Error('Supabase doit être configuré avant les vraies annotations.');const b=$('#background').value,n=$('#annotatorName').value.trim();const r=first(await rpc('register_annotator',{p_display_name:n||null,p_background:b,p_expertise_level:bgLevel(b),p_consent:true}));if(!r?.annotator_id)throw new Error('Impossible de créer le profil.');state.profile={annotator_id:r.annotator_id,access_token:r.access_token,display_name:n,background:b,expertise_level:bgLevel(b),submitted_count:0,created_at:now()};save(STORE.profile,state.profile);return state.profile}
function updateProgress(){const c=Number(state.session.count||0);$('#sessionProgressText').textContent=`${c} cas`;const t=Number(state.profile?.submitted_count||state.receipts.length||0);$('#lifetimeProgress').textContent=`${t} cas annoté${t>1?'s':''} au total`}
async function refreshProgress(){if(!state.profile?.annotator_id)return;try{const r=first(await rpc('get_my_progress',{p_annotator_id:state.profile.annotator_id,p_access_token:state.profile.access_token}));if(r){state.profile.submitted_count=Number(r.submitted_count||0);save(STORE.profile,state.profile);updateProgress()}}catch(e){console.warn(e)}}
function showWelcomeError(m){const e=$('#welcomeError');e.textContent=m;e.classList.remove('hidden')} function clearWelcomeError(){$('#welcomeError').classList.add('hidden')}
function tr(v){if(v==null)return'';if(typeof v==='string')return v;return v[state.lang]||v.fr||v.en||''}
function evid(){return Array.isArray(state.currentCase?.evidence)?state.currentCase.evidence:[]}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} const attr=esc;
function labelEvidence(e){return `${e.id} — ${tr(e.source_type)||'Source'} — ${tr(e.source_title)||'Sans titre'}`}
function cardBody(e){return `<div class="evidence-card-body"><div class="source-line"><span class="micro-label">Source</span><strong>${esc(tr(e.source_type))}${tr(e.source_title)?` · ${esc(tr(e.source_title))}`:''}</strong></div><div class="excerpt-line"><span class="micro-label">Ce qu’elle dit</span><span>${esc(tr(e.text))}</span></div></div>`}
function renderCurrent(){const c=state.currentCase;$('#practiceBanner').classList.toggle('hidden',state.mode!=='practice');$('#skipCaseBtn').classList.toggle('hidden',state.mode==='practice');$('#pauseBtn').classList.toggle('hidden',state.mode==='practice');$('#caseModeEyebrow').textContent=state.mode==='practice'?'CAS D’ENTRAÎNEMENT':'CAS EN COURS';$('#caseDomainLine').textContent=state.mode==='practice'?`Entraînement ${state.practice.done.length+1} sur 5 maximum`:`${c.benchmark||c.domain||''}${c.difficulty?` · ${c.difficulty}`:''}`;
 const isQA=c.case_type==='qa';$('#questionWrap').classList.toggle('hidden',!isQA);$('#claimText').classList.toggle('hidden',isQA);$('#claimLabel').textContent=isQA?'Cas de question-réponse':'Affirmation à évaluer';if(isQA){$('#questionText').textContent=tr(c.question);$('#proposedAnswerText').textContent=tr(c.proposed_answer)}else{$('#claimText').textContent=tr(c.claim)}
 const note=$('#translationNote');if(c.translation_note_fr&&state.lang==='fr'){note.textContent=c.translation_note_fr;note.classList.remove('hidden')}else note.classList.add('hidden');$('#langBtn').textContent=state.lang==='fr'?'Voir l’original anglais':'Voir la traduction française';
 const ov=$('#evidenceOverview');ov.innerHTML='';evid().forEach(e=>{const a=document.createElement('article');a.className='evidence-card overview-card';a.innerHTML=`<div class="evidence-head"><span class="evidence-id">${esc(e.id)}</span><span class="source-type">${esc(tr(e.source_type))}</span></div>${cardBody(e)}`;ov.appendChild(a)});
 const el=$('#evidenceList');el.innerHTML='';evid().forEach(e=>{const l=document.createElement('label');l.className='evidence-select';l.innerHTML=`<input type="checkbox" name="relevantEvidence" value="${attr(e.id)}"><div><div class="evidence-source"><strong>Extrait ${esc(e.id)}</strong></div>${cardBody(e)}</div>`;el.appendChild(l)});
 const cl=$('#contradictionList');cl.innerHTML='';evid().forEach(e=>{const l=document.createElement('label');l.className='evidence-select compact-select';l.innerHTML=`<input type="checkbox" name="contradictionEvidence" value="${attr(e.id)}"><div><div class="evidence-source"><strong>Extrait ${esc(e.id)}</strong></div>${cardBody(e)}</div>`;cl.appendChild(l)});
 $('#warrantsContainer').innerHTML='';$('#dependencyPairs').innerHTML='';$$('input[name="verdict"],input[name="action"]').forEach(x=>x.checked=false);$('#confidenceRange').value=3;$('#notes').value='';updateJustification();if(state.mode==='real'){const d=state.drafts[state.currentAssignment?.assignment_id];if(d)restore(d)}
}
function updateJustification(){const v=getRadio('verdict'),needed=['SUPPORT','CONTRADICT'].includes(v),b=$('#justificationBlock');b.classList.toggle('soft-disabled',!needed);$('#addWarrantBtn').disabled=!needed;let n=b.querySelector('.verdict-note');if(!needed){if(!n){n=document.createElement('div');n.className='callout compact verdict-note';n.textContent='Cette étape n’est pas nécessaire si tu as choisi « Pas assez d’information » ou « Je n’arrive pas à trancher ».';b.appendChild(n)}}else{n?.remove();if(!$('#warrantsContainer').children.length)addWarrant()}}
function selected(card){return $$('.warrant-evidence:checked',card).map(x=>x.value).sort()}
function minimalUI(card,preset=null){const ids=selected(card),box=$('.minimality-box',card);if(!ids.length){box.innerHTML='<div class="micro muted-text">Choisis d’abord un ou plusieurs extraits.</div>';return}if(ids.length===1){box.innerHTML='<div class="callout compact good-note">Un seul extrait : s’il suffit vraiment, l’ensemble est automatiquement minimal.</div>';card.dataset.minimal='true';return}const yes=preset===true||(preset===null&&card.dataset.minimal==='true'),no=preset===false||(preset===null&&card.dataset.minimal==='false');box.innerHTML=`<strong>Peut-on retirer un des extraits choisis tout en gardant une justification suffisante ?</strong><div class="choice-grid two-compact"><label class="choice mini-choice"><input type="radio" name="minimal-${attr(card.dataset.wid)}" value="yes" ${yes?'checked':''}><span><strong>Non</strong><small>Chaque extrait est nécessaire.</small></span></label><label class="choice mini-choice"><input type="radio" name="minimal-${attr(card.dataset.wid)}" value="no" ${no?'checked':''}><span><strong>Oui / je ne suis pas sûr</strong><small>Il y a peut-être un extrait inutile.</small></span></label></div>`;$$('input[type="radio"]',box).forEach(r=>r.onchange=()=>{card.dataset.minimal=r.value==='yes'?'true':'false';draft()})}
function addWarrant(data=null){const card=document.createElement('div');card.className='warrant-card';card.dataset.wid=crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());if(typeof data?.minimal==='boolean')card.dataset.minimal=data.minimal?'true':'false';const checks=evid().map(e=>`<label class="mini-check justification-check"><input type="checkbox" class="warrant-evidence" value="${attr(e.id)}" ${data?.evidence_ids?.includes(e.id)?'checked':''}><span><strong>${esc(e.id)}</strong> — ${esc(tr(e.text))}</span></label>`).join('');card.innerHTML=`<div class="warrant-top"><h3>Justification suffisante</h3><button class="icon-btn remove-warrant" type="button">×</button></div><div class="check-grid">${checks}</div><div class="minimality-box"></div>`;$('#warrantsContainer').appendChild(card);minimalUI(card,typeof data?.minimal==='boolean'?data.minimal:null);$('.remove-warrant',card).onclick=()=>{card.remove();draft()};$$('.warrant-evidence',card).forEach(x=>x.onchange=()=>{card.dataset.minimal='';minimalUI(card);draft()})}
function addDependency(data=null){const r=document.createElement('div');r.className='dependency-row';const opts=evid().map(e=>`<option value="${attr(e.id)}">${esc(labelEvidence(e))}</option>`).join('');r.innerHTML=`<select class="input dep-a"><option value="">Première source…</option>${opts}</select><select class="input dep-b"><option value="">Deuxième source…</option>${opts}</select><input class="input reason" placeholder="Ex. B cite A ; même étude ; même cohorte…"><button class="icon-btn dep-remove">×</button>`;$('#dependencyPairs').appendChild(r);if(data){$('.dep-a',r).value=data.a||'';$('.dep-b',r).value=data.b||'';$('.reason',r).value=data.reason||''}$('.dep-remove',r).onclick=()=>{r.remove();draft()}}
function getRadio(n){return $(`input[name="${n}"]:checked`)?.value||null}function getChecked(n){return $$(`input[name="${n}"]:checked`).map(x=>x.value)}
function collect(){const warrants=$$('.warrant-card').map(c=>({evidence_ids:selected(c),minimal:selected(c).length===1?true:(c.dataset.minimal==='true'?true:c.dataset.minimal==='false'?false:null)}));const deps=$$('.dependency-row').map(r=>({a:$('.dep-a',r).value,b:$('.dep-b',r).value,reason:$('.reason',r).value.trim()})).filter(d=>d.a||d.b||d.reason);return {schema_version:'5.2',case_id:state.currentCase?.id||null,verdict:getRadio('verdict'),relevant_evidence:getChecked('relevantEvidence'),warrants,contradictions:getChecked('contradictionEvidence'),dependencies:deps,action:getRadio('action'),confidence:Number($('#confidenceRange').value),notes:$('#notes').value.trim(),language_view:state.lang,started_at:state.currentStartedAt,finished_at:now(),warrant_signature:warrants.map(w=>w.evidence_ids.join('+')).sort()}}
function validate(a){const er=[];if(!a.verdict)er.push('Choisis ton jugement.');if(!a.action)er.push('Choisis ce que devrait faire un système prudent.');if(['SUPPORT','CONTRADICT'].includes(a.verdict)&&!a.warrants.some(w=>w.evidence_ids.length))er.push('Indique au moins une justification suffisante.');a.warrants.forEach((w,i)=>{if(!w.evidence_ids.length)er.push(`La justification ${i+1} ne contient aucun extrait.`);if(w.evidence_ids.length>1&&w.minimal===null)er.push(`Pour la justification ${i+1}, indique si un extrait peut être retiré.`)});a.dependencies.forEach((d,i)=>{if(!d.a||!d.b)er.push(`Complète les deux sources de la dépendance ${i+1}.`);if(d.a&&d.a===d.b)er.push(`La dépendance ${i+1} doit relier deux sources différentes.`);if(!d.reason)er.push(`Explique brièvement la dépendance ${i+1}.`)});return er}
function showErrors(er){const e=$('#validationMessage');if(!er.length){e.classList.add('hidden');e.innerHTML='';return}e.innerHTML=`<strong>Il reste un petit point à vérifier :</strong><ul>${er.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;e.classList.remove('hidden');e.scrollIntoView({behavior:'smooth',block:'center'})}
function draft(){if(state.mode!=='real'||!state.currentAssignment?.assignment_id)return;try{state.drafts[state.currentAssignment.assignment_id]=collect();save(STORE.drafts,state.drafts)}catch{}}
function restore(d){if(!d)return;const v=$(`input[name="verdict"][value="${d.verdict||''}"]`);if(v)v.checked=true;const a=$(`input[name="action"][value="${d.action||''}"]`);if(a)a.checked=true;(d.relevant_evidence||[]).forEach(id=>{const x=$(`input[name="relevantEvidence"][value="${id}"]`);if(x)x.checked=true});(d.contradictions||[]).forEach(id=>{const x=$(`input[name="contradictionEvidence"][value="${id}"]`);if(x)x.checked=true});updateJustification();$('#warrantsContainer').innerHTML='';(d.warrants||[]).forEach(addWarrant);if(['SUPPORT','CONTRADICT'].includes(d.verdict)&&!(d.warrants||[]).length)addWarrant();(d.dependencies||[]).forEach(addDependency);$('#confidenceRange').value=d.confidence||3;$('#notes').value=d.notes||'';state.currentStartedAt=d.started_at||state.currentStartedAt}
async function startReal(){try{await ensureProfile();state.mode='real';setScreen('annotate');await refreshProgress();await loadReal()}catch(e){showWelcomeError(e.message);setScreen('welcome')}}
async function loadReal(){state.mode='real';$('#annotationPanel').classList.add('hidden');$('#noCase').classList.add('hidden');$('#loadingCase').classList.remove('hidden');showErrors([]);try{const row=first(await rpc('assign_next_case',{p_annotator_id:state.profile.annotator_id,p_access_token:state.profile.access_token}));$('#loadingCase').classList.add('hidden');if(!row?.assignment_id){$('#noCase').classList.remove('hidden');return}state.currentAssignment=row;state.currentCase={id:row.case_id,domain:row.domain,stratum:row.stratum,difficulty:row.difficulty,...(typeof row.payload==='string'?JSON.parse(row.payload):row.payload)};state.currentStartedAt=now();state.lang='fr';renderCurrent();$('#annotationPanel').classList.remove('hidden')}catch(e){$('#loadingCase').classList.add('hidden');$('#noCase').classList.remove('hidden');$('#noCase h2').textContent='Impossible de charger un cas';$('#noCase p').textContent=e.message}}
function startPractice(){validateLocalProfile();const available=TRAIN.filter(c=>!state.practice.done.includes(c.id));if(!available.length||state.practice.done.length>=5){startReal();return}state.mode='practice';state.currentAssignment=null;state.currentCase=JSON.parse(JSON.stringify(available[0]));state.currentCase.benchmark='Entraînement';state.currentStartedAt=now();state.lang='fr';setScreen('annotate');renderCurrent();$('#annotationPanel').classList.remove('hidden');$('#loadingCase').classList.add('hidden');$('#noCase').classList.add('hidden')}
function practiceFeedback(a){const ans=state.currentCase.answer;const verdictMap={SUPPORT:'Soutenu',CONTRADICT:'Contredit',INSUFFICIENT:'Pas assez d’information',UNCERTAIN:'Impossible à trancher'};const actionMap={CERTIFY:'Certifier',SEARCH_MORE:'Chercher davantage',ABSTAIN:'S’abstenir',ESCALATE:'Demander une revue experte'};const sets=(ans.warrants||[]).length?ans.warrants.map(x=>`{${x.join(', ')}}`).join(' ou '):'Aucune justification suffisante';const deps=(ans.dependencies||[]).length?ans.dependencies.map(d=>`${d.a}–${d.b}`).join(', '):'Aucune';$('#practiceFeedback').innerHTML=`<p><span class="correct-chip">Correction</span></p><div class="feedback-grid"><div class="feedback-item"><strong>Jugement attendu</strong>${esc(verdictMap[ans.verdict])}</div><div class="feedback-item"><strong>Extraits utiles</strong>${esc((ans.relevant||[]).join(', ')||'Aucun')}</div><div class="feedback-item"><strong>Plus petit(s) ensemble(s) suffisant(s)</strong>${esc(sets)}</div><div class="feedback-item"><strong>Extrait(s) contradictoire(s)</strong>${esc((ans.contradictions||[]).join(', ')||'Aucun')}</div><div class="feedback-item"><strong>Sources dépendantes</strong>${esc(deps)}</div><div class="feedback-item"><strong>Action attendue</strong>${esc(actionMap[ans.action])}</div></div><p><strong>Pourquoi ?</strong> ${esc(ans.explanation_fr)}</p>`;$('#nextPracticeBtn').classList.toggle('hidden',state.practice.done.length>=5);setScreen('practice-feedback')}
async function submit(){if(state.submitting)return;const a=collect(),er=validate(a);if(er.length){showErrors(er);return}if(state.mode==='practice'){if(!state.practice.done.includes(state.currentCase.id))state.practice.done.push(state.currentCase.id);save(STORE.practice,state.practice);practiceFeedback(a);return}state.submitting=true;$('#submitBtn').disabled=true;$('#submitBtn').textContent='Envoi…';draft();try{const row=first(await rpc('submit_annotation',{p_annotator_id:state.profile.annotator_id,p_access_token:state.profile.access_token,p_assignment_id:state.currentAssignment.assignment_id,p_payload:a}));state.receipts.push({case_id:state.currentCase.id,submitted_at:now(),annotation:a});save(STORE.receipts,state.receipts);delete state.drafts[state.currentAssignment.assignment_id];save(STORE.drafts,state.drafts);state.session.count=Number(state.session.count||0)+1;save(STORE.session,state.session);state.profile.submitted_count=Number(row?.submitted_count??state.profile.submitted_count+1);save(STORE.profile,state.profile);state.currentAssignment=null;state.currentCase=null;updateProgress();setScreen('done')}catch(e){showErrors([`L’envoi a échoué : ${e.message}. Ton brouillon reste sauvegardé.`])}finally{state.submitting=false;$('#submitBtn').disabled=false;$('#submitBtn').textContent='Envoyer cette annotation →'}}
async function skipReal(){if(state.mode!=='real'||!state.currentAssignment)return;$('#confirmSkipBtn').disabled=true;try{await rpc('skip_assignment',{p_annotator_id:state.profile.annotator_id,p_access_token:state.profile.access_token,p_assignment_id:state.currentAssignment.assignment_id});delete state.drafts[state.currentAssignment.assignment_id];save(STORE.drafts,state.drafts);state.currentAssignment=null;state.currentCase=null;$('#skipDialog').close();await loadReal()}catch(e){$('#skipDialog').close();showErrors([`Impossible de passer ce cas : ${e.message}`])}finally{$('#confirmSkipBtn').disabled=false}}
function refreshDone(){$('#doneHeading').textContent='Ta contribution est enregistrée.';$('#continueBtn').classList.remove('hidden');$('#stopBtn').classList.remove('hidden');const s=Number(state.session.count||0);$('#doneSessionCount').textContent=String(s);$('#doneLifetimeCount').textContent=String(state.profile?.submitted_count||state.receipts.length||0);if(s>=5){$('#doneMessage').textContent=`Merci pour ces ${s} cas. Si ton attention baisse, le mieux est de t’arrêter ici.`;$('#restNote').textContent='La qualité compte plus que le nombre. Tout ce qui a déjà été envoyé est enregistré.'}else{$('#doneMessage').textContent='Merci. Une seule annotation est déjà utile. Tu peux t’arrêter ici sans aucun problème.';$('#restNote').textContent='Tu peux fermer cette page quand tu veux. Tout ce qui a déjà été envoyé est enregistré.'}}
function download(){const b=new Blob([JSON.stringify({exported_at:now(),annotator:{display_name:state.profile?.display_name||null,background:state.profile?.background||null,annotator_id:state.profile?.annotator_id||null},annotations:state.receipts},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`annotations_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)}
function wire(){$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#toPracticeIntroBtn').onclick=()=>{clearWelcomeError();try{validateLocalProfile();setScreen('practice-intro')}catch(e){showWelcomeError(e.message)}};$('#startPracticeBtn').onclick=()=>{try{startPractice()}catch(e){showWelcomeError(e.message);setScreen('welcome')}};$('#skipPracticeBtn').onclick=startReal;$('#practiceToRealBtn').onclick=startReal;$('#nextPracticeBtn').onclick=()=>{try{startPractice()}catch(e){showWelcomeError(e.message);setScreen('welcome')}};$('#langBtn').onclick=()=>{state.lang=state.lang==='fr'?'en':'fr';renderCurrent()};$('#skipCaseBtn').onclick=()=>$('#skipDialog').showModal();$('#confirmSkipBtn').onclick=skipReal;$('#addWarrantBtn').onclick=()=>addWarrant();$$('input[name="verdict"]').forEach(x=>x.onchange=()=>{updateJustification();draft()});$('#addDependencyBtn').onclick=()=>addDependency();$('#saveDraftBtn').onclick=()=>{draft();const b=$('#saveDraftBtn'),o=b.textContent;b.textContent='Brouillon sauvegardé ✓';setTimeout(()=>b.textContent=o,1000)};$('#submitBtn').onclick=submit;$('#pauseBtn').onclick=()=>{draft();setScreen('done');$('#doneHeading').textContent='Ton brouillon est sauvegardé.';$('#doneMessage').textContent='Le cas en cours n’a pas été envoyé. Tu pourras le reprendre depuis ce navigateur.'};$('#continueBtn').onclick=()=>{setScreen('annotate');loadReal()};$('#stopBtn').onclick=()=>{$('#doneMessage').textContent='Merci pour ta contribution. Tu peux fermer cette page maintenant.';$('#continueBtn').classList.add('hidden');$('#stopBtn').classList.add('hidden')};$('#downloadMyDataBtn').onclick=download;$$('[data-go]').forEach(b=>b.onclick=()=>setScreen(b.dataset.go));document.addEventListener('change',e=>{if(state.mode==='real'&&e.target.matches('input,select,textarea'))draft()});addEventListener('beforeunload',draft)}
async function init(){const day=now().slice(0,10),old=String(state.session.started_at||'').slice(0,10);if(old&&old!==day){state.session={count:0,started_at:now()};save(STORE.session,state.session)}wire();prefill();updateProgress();await checkBackend();if(state.profile)await refreshProgress()}
init();
})();
