(() => {
  'use strict';

  const ALL_TAGS = ['69', 'alcool', 'anal', 'anulingus', 'baiser', 'bandeau', 'body_shot', 'caresse', 'caresses', 'clito', 'compliment', 'cowgirl', 'cunnilingus', 'danse', 'denial', 'déshabillage', 'dirtytalk', 'doigts', 'edging', 'eye_contact', 'fantasy', 'fellation', 'fessée', 'grinding', 'hairpulling', 'hardcore', 'huile', 'ice', 'intense', 'jeu', 'jouet', 'lapdance', 'levrette', 'lubrifiant', 'massage', 'masturbation', 'menottes', 'missionnaire', 'oral', 'plug', 'plume', 'prep', 'pénétration', 'rétention', 'seins', 'sensuel', 'sexe', 'simulation', 'slow', 'softcore', 'striptease', 'teasing', 'temperature_play', 'titjob', 'vibration', 'visuel', 'whisper'];
  const GAGES = Array.isArray(window.GAGES) ? window.GAGES : [];
  const DRINK_SUGGESTIONS = [
    "Prenez une petite gorgée de votre boisson préférée ensemble.",
    "L'un de vous doit servir une gorgée à l'autre.",
    "Trinquez à votre complicité et buvez une gorgée.",
    "Une petite pause fraîcheur ? Une gorgée pour chacun.",
    "L'Homme embrasse la Femme, puis les deux boivent une gorgée."
  ];

  const app = document.getElementById('app');
  const stopBtn = document.getElementById('stopBtn');
  const successSound = document.getElementById('successSound');
  const balloons = document.getElementById('balloons');
  let timerHandle = null;
  let timerEndHandle = null;

  function initialState() {
    return {
      game_started: false,
      current_phase: 1,
      history: [],
      next_player: 'Homme',
      current_gage: null,
      start_time: null,
      drink_counter: 0,
      total_gages_target: 30,
      phase_distribution: {1:10,2:8,3:6,4:4,5:2},
      total_done: 0,
      names: {Homme:'Iz', Femme:'Fa'},
      accepted_tags: [...ALL_TAGS],
      sex_finality: true,
      gages_in_current_phase: 0,
      timer_active: false,
      timer_seconds: 0,
      game_over: false,
      drink_suggestion: null,
      timer_complete: false
    };
  }

  let state = initialState();

  function escapeHtml(value) {
    return String(value).replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  }

  function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  function calculateDistribution(total) {
    // Exact values generated by Python's round() for the select_slider options.
    const table = {
      15:[5,4,3,2,1], 20:[7,5,4,3,1], 25:[8,7,5,3,2], 30:[10,8,6,4,2], 35:[12,9,7,5,2],
      40:[13,11,8,5,3], 45:[15,12,9,6,3], 50:[17,13,10,7,3], 55:[18,15,11,7,4], 60:[20,16,12,8,4]
    };
    const vals = table[total] || table[30];
    return {1:vals[0],2:vals[1],3:vals[2],4:vals[3],5:vals[4]};
  }

  function filterGages(acceptedTags) {
    const accepted = new Set(acceptedTags);
    return GAGES.filter(g => Array.from(g.tags).every(tag => accepted.has(tag))); // Array.from preserves Python iteration semantics even for the 4 string-valued tag entries
  }

  function getNextGage(currentPhase, nextPlayer, history, acceptedTags) {
    const historySet = new Set(history);
    const available = filterGages(acceptedTags)
      .filter(g => g.phase === currentPhase && g.target === nextPlayer && !historySet.has(g.id))
      .sort((a,b) => a.hot - b.hot);
    if (!available.length) return null;

    const phaseIds = new Set(GAGES.filter(g => g.phase === currentPhase).map(g => g.id));
    const gagesDoneInPhase = history.reduce((n,id) => n + (phaseIds.has(id) ? 1 : 0), 0);
    const progression = Math.min(gagesDoneInPhase / 10.0, 1.0);
    let windowSize = Math.floor(available.length * (0.4 + 0.6 * progression));
    windowSize = Math.max(windowSize, 1);
    const selectionPool = available.slice(0, windowSize);
    return selectionPool[Math.floor(Math.random() * selectionPool.length)];
  }

  function getDrinkSuggestion() {
    return DRINK_SUGGESTIONS[Math.floor(Math.random() * DRINK_SUGGESTIONS.length)];
  }

  function formatGageText(text) {
    const fName = state.names.Femme;
    const hName = state.names.Homme;
    let out = text.replace(/la [Ff]emme/g, fName);
    out = out.replace(/l['’][Hh]omme/g, hName);
    return out;
  }

  function clearTimer() {
    if (timerHandle) clearInterval(timerHandle);
    if (timerEndHandle) clearTimeout(timerEndHandle);
    timerHandle = null;
    timerEndHandle = null;
    state.timer_active = false;
    state.timer_complete = false;
  }

  function resetGame() {
    clearTimer();
    state = initialState();
    render();
    window.scrollTo({top:0, behavior:'smooth'});
  }

  function nextTurn() {
    if (!state.current_gage) return;
    state.history.push(state.current_gage.id);
    state.next_player = state.next_player === 'Homme' ? 'Femme' : 'Homme';
    state.drink_counter += 1;
    state.gages_in_current_phase += 1;
    state.total_done += 1;

    const targetForCurrentPhase = state.phase_distribution[state.current_phase] ?? 1;
    if (state.gages_in_current_phase >= targetForCurrentPhase) {
      if (state.current_phase < 5) {
        if (state.current_phase === 4 && !state.sex_finality) {
          // Rester en phase 4 si pas de finalité sexe
        } else {
          state.current_phase += 1;
          state.gages_in_current_phase = 0;
        }
      } else {
        state.game_over = true;
        render();
        return;
      }
    }

    state.current_gage = getNextGage(state.current_phase, state.next_player, state.history, state.accepted_tags);
    maybeSetDrinkSuggestion();
    render();
  }

  function skipTurn() {
    state.current_gage = getNextGage(state.current_phase, state.next_player, state.history, state.accepted_tags);
    state.drink_suggestion = null;
    maybeSetDrinkSuggestion();
    render();
  }

  function maybeSetDrinkSuggestion() {
    state.drink_suggestion = null;
    if (state.drink_counter >= 4 && Math.random() > 0.5) {
      state.drink_suggestion = getDrinkSuggestion();
      state.drink_counter = 0;
    }
  }

  function startGame() {
    const nameH = document.getElementById('nameHomme').value;
    const nameF = document.getElementById('nameFemme').value;
    const selected = [...document.querySelectorAll('input[name="acceptedTag"]:checked')].map(el => el.value);
    const total = Number(document.getElementById('gageRange').value);
    const sexFinality = document.getElementById('sexFinality').checked;
    const error = document.getElementById('setupError');

    if (!selected.length) {
      error.hidden = false;
      return;
    }

    state.names.Homme = nameH;
    state.names.Femme = nameF;
    state.accepted_tags = selected;
    state.total_gages_target = total;
    state.phase_distribution = calculateDistribution(total);
    state.sex_finality = sexFinality;
    state.game_started = true;
    state.start_time = Date.now();
    state.total_done = 0;
    state.gages_in_current_phase = 0;
    state.current_phase = 1;
    state.current_gage = getNextGage(state.current_phase, state.next_player, state.history, state.accepted_tags);
    state.drink_suggestion = null;
    render();
  }

  function startTimer(duration) {
    if (state.timer_active) return;
    state.timer_active = true;
    state.timer_complete = false;
    state.timer_seconds = duration;
    render();

    const startedAt = Date.now();
    timerHandle = setInterval(() => {
      const elapsed = Math.floor((Date.now() - startedAt) / 1000);
      state.timer_seconds = Math.max(duration - elapsed, 0);
      updateTimerDOM(duration);
      if (state.timer_seconds <= 0) {
        clearInterval(timerHandle);
        timerHandle = null;
        finishTimer();
      }
    }, 200);
  }

  function updateTimerDOM(duration) {
    const display = document.getElementById('timerDisplay');
    const fill = document.getElementById('timerFill');
    if (!display || !fill) return;
    const mins = Math.floor(state.timer_seconds / 60);
    const secs = state.timer_seconds % 60;
    display.textContent = `${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;
    fill.style.width = `${Math.max(0, Math.min(100, (state.timer_seconds / duration) * 100))}%`;
  }

  function finishTimer() {
    state.timer_active = false;
    state.timer_complete = true;
    try { successSound.currentTime = 0; successSound.play().catch(() => {}); } catch (_) {}
    launchBalloons();
    render();
    timerEndHandle = setTimeout(() => {
      state.timer_complete = false;
      render();
    }, 3000);
  }

  function launchBalloons() {
    balloons.innerHTML = '';
    balloons.classList.add('active');
    for (let i=0;i<26;i++) {
      const b = document.createElement('div');
      b.className = 'balloon';
      b.style.left = `${Math.random()*96}%`;
      b.style.animationDelay = `${Math.random()*.7}s`;
      b.style.animationDuration = `${2.2 + Math.random()*1.6}s`;
      b.style.setProperty('--drift', `${-80 + Math.random()*160}px`);
      b.style.background = ['#d4af37','#ff3fa0','#a761ff','#f2de89'][i%4];
      balloons.appendChild(b);
    }
    setTimeout(() => { balloons.classList.remove('active'); balloons.innerHTML=''; }, 4000);
  }

  function renderSetup() {
    const tags = ALL_TAGS.map(tag => `
      <label class="tag-choice"><input type="checkbox" name="acceptedTag" value="${escapeHtml(tag)}" checked><span>${escapeHtml(tag)}</span></label>
    `).join('');
    app.innerHTML = `
      <h1>🔥 Hot Escalation</h1>
      <div class="setup-subtitle">Préparez votre soirée...</div>
      <section class="panel">
        <div class="form-grid">
          <div class="field"><label for="nameHomme">Prénom Lui</label><input class="text-input" id="nameHomme" type="text" value="Iz" autocomplete="off"></div>
          <div class="field"><label for="nameFemme">Prénom Elle</label><input class="text-input" id="nameFemme" type="text" value="Fa" autocomplete="off"></div>
        </div>
        <hr class="divider">
        <div class="section-title">Tags acceptés</div>
        <div class="field-label">Cochez ce que vous acceptez ce soir :</div>
        <div class="tags-box"><div class="tags-grid">${tags}</div></div>
        <div class="controls-grid">
          <div class="field">
            <label for="gageRange">Nombre de gages</label>
            <div class="range-wrap"><input id="gageRange" type="range" min="15" max="60" step="5" value="30"><div id="gageValue" class="range-value">30</div></div>
          </div>
          <div class="field">
            <div class="field-label">Finalité Sexe</div>
            <div class="toggle-row"><span></span><label class="switch"><input id="sexFinality" type="checkbox" checked><span class="slider"></span></label></div>
          </div>
        </div>
        <div id="setupError" class="error-box" hidden>Veuillez choisir au moins quelques tags.</div>
        <button id="startBtn" class="action-btn primary-start" type="button">COMMENCER L'ASCENSION</button>
      </section>`;

    document.getElementById('gageRange').addEventListener('input', e => { document.getElementById('gageValue').textContent = e.target.value; });
    document.getElementById('startBtn').addEventListener('click', startGame);
  }

  function renderGameOver() {
    app.innerHTML = `
      <h1>❤️ Ascension Terminée</h1>
      <div class="gage-card game-over-card"><div class="gage-text">L'ascension est terminée. Profitez de ce moment l'un avec l'autre...</div></div>
      <button id="restartBtn" class="action-btn" type="button">RECOMMENCER</button>`;
    document.getElementById('restartBtn').addEventListener('click', resetGame);
  }

  function timerHtml(gage) {
    const duration = Number(gage.duration || 0);
    if (duration <= 0) return '';
    if (state.timer_active) {
      const mins = Math.floor(state.timer_seconds / 60);
      const secs = state.timer_seconds % 60;
      const pct = (state.timer_seconds / duration) * 100;
      return `<div class="timer-section">
        <div id="timerDisplay" class="timer-display">${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}</div>
        <div class="progress-track timer-progress"><div id="timerFill" class="progress-fill" style="width:${pct}%"></div></div>
      </div>`;
    }
    if (state.timer_complete) {
      return `<div class="timer-section"><div class="success-box">Temps écoulé !</div></div>`;
    }
    return `<div class="timer-section"><button id="timerStartBtn" class="action-btn" type="button">⏱️ DÉMARRER LE MINUTEUR (${duration}s)</button></div>`;
  }

  function renderAdvanced() {
    return `<details class="advanced">
      <summary>Contrôles avancés</summary>
      <div class="advanced-content field">
        <label for="phaseInput">Changer de phase manuellement</label>
        <input id="phaseInput" class="number-input" type="number" min="1" max="5" step="1" value="${state.current_phase}">
      </div>
    </details>`;
  }

  function renderGame() {
    const done = state.total_done;
    const total = state.total_gages_target;
    const remaining = Math.max(total - done, 0);
    const progress = total > 0 ? Math.max(0, Math.min(100, done / total * 100)) : 0;

    if (state.current_gage) {
      const g = state.current_gage;
      const targetName = state.names[g.target];
      const targetClass = g.target === 'Homme' ? 'player-homme' : 'player-femme';
      const displayText = formatGageText(g.text);
      const tags = Array.from(g.tags).map(t => `<span class="tag-badge">#${escapeHtml(t)}</span>`).join('');
      const drink = state.drink_suggestion ? `<div class="drink-suggestion">🍹 ${escapeHtml(state.drink_suggestion)}</div>` : '';
      const disableActions = state.timer_active ? 'disabled' : '';

      app.innerHTML = `
        <div class="phase-info">Phase ${state.current_phase} • ${done} gages faits / ${remaining} restants</div>
        <div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div>
        <div class="gage-card">
          <div class="player-name ${targetClass}">${escapeHtml(targetName)}</div>
          <div class="gage-text">${escapeHtml(displayText)}</div>
          <div class="tags-container">${tags}</div>
        </div>
        ${drink}
        ${timerHtml(g)}
        <div class="game-actions">
          <button id="nextBtn" class="action-btn" type="button" ${disableActions}>SUIVANT</button>
          <button id="skipBtn" class="action-btn" type="button" ${disableActions}>PASSER</button>
        </div>
        ${renderAdvanced()}`;

      const timerBtn = document.getElementById('timerStartBtn');
      if (timerBtn) timerBtn.addEventListener('click', () => startTimer(Number(g.duration)));
      document.getElementById('nextBtn').addEventListener('click', () => { clearTimer(); nextTurn(); });
      document.getElementById('skipBtn').addEventListener('click', () => { clearTimer(); skipTurn(); });
    } else {
      app.innerHTML = `
        <div class="phase-info">Phase ${state.current_phase} • ${done} gages faits / ${remaining} restants</div>
        <div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div>
        <div class="gage-card empty-card"><div class="gage-text">Plus de gages disponibles avec vos filtres dans cette phase.</div></div>
        <button id="nextPhaseBtn" class="action-btn" type="button">PASSER À LA PHASE SUIVANTE</button>
        ${renderAdvanced()}`;
      document.getElementById('nextPhaseBtn').addEventListener('click', () => {
        state.current_phase = Math.min(state.current_phase + 1, 5);
        state.gages_in_current_phase = 0;
        state.current_gage = getNextGage(state.current_phase, state.next_player, state.history, state.accepted_tags);
        state.drink_suggestion = null;
        render();
      });
    }

    const phaseInput = document.getElementById('phaseInput');
    phaseInput.addEventListener('change', e => {
      let newPhase = Number(e.target.value);
      newPhase = Math.max(1, Math.min(5, Number.isFinite(newPhase) ? newPhase : state.current_phase));
      e.target.value = newPhase;
      if (newPhase !== state.current_phase) {
        clearTimer();
        state.current_phase = newPhase;
        state.gages_in_current_phase = 0;
        state.current_gage = getNextGage(state.current_phase, state.next_player, state.history, state.accepted_tags);
        state.drink_suggestion = null;
        render();
      }
    });
  }

  function render() {
    if (!state.game_started) renderSetup();
    else if (state.game_over) renderGameOver();
    else renderGame();
  }

  stopBtn.addEventListener('click', resetGame);
  render();
})();
